---
title: "Liam Kettle's CV"
author: Liam Kettle
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv-no-sidebar.css', 'resume']
    self_contained: true
---
```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data/",  
  pdf_mode = params$pdf_mode
)

```

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Main
================================================================================

**Liam Kettle, M.S.** {#title}
--------------------------------------------------------------------------------
```{r}
CV %<>% print_contact_info()
```

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')

```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

## Select Publications {data-icon="book" data-concise="true"}

```{r}
CV %<>% print_academia_section('academic_articles')
```

## Select Awards {data-icon="award"}

```{r}
CV %<>% print_minor_section('award')
```

## Professional Service & Leadership {data-icon="user-tie"}

```{r}
CV %<>% print_section('service')
```